#!/usr/bin/env bash
# =============================================================================
#  VitalHealth — E2E Cloud Server Setup Script
#  Run this ONCE on a fresh Ubuntu 22.04 VM to configure everything.
#
#  Usage:
#    chmod +x deployment/setup.sh
#    ./deployment/setup.sh
#
#  What it does:
#    1. Installs system packages
#    2. Sets up Python 3.11 venv
#    3. Installs Python dependencies
#    4. Prompts for API key and writes .env
#    5. Installs systemd service
#    6. Configures Nginx
#    7. Sets up daily backup cron
#    8. Starts everything and runs a health check
# =============================================================================

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
GREEN="\033[0;32m"; YELLOW="\033[1;33m"; RED="\033[0;31m"; NC="\033[0m"
ok()   { echo -e "${GREEN}✔  $*${NC}"; }
info() { echo -e "${YELLOW}→  $*${NC}"; }
fail() { echo -e "${RED}✘  $*${NC}"; exit 1; }

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY_DIR="$PROJECT_DIR/deployment"

echo ""
echo "============================================================"
echo "  VitalHealth — BioGears Cloud Setup"
echo "  Project: $PROJECT_DIR"
echo "============================================================"
echo ""

# ── Guard: must run as non-root ubuntu user ───────────────────────────────────
if [[ "$EUID" -eq 0 ]]; then
  fail "Do NOT run as root. Run as ubuntu: ./deployment/setup.sh"
fi

# ── Step 1: System packages ────────────────────────────────────────────────────
info "Step 1/8 — Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    git python3.11 python3.11-venv python3-pip \
    nginx certbot python3-certbot-nginx \
    build-essential libssl-dev libffi-dev \
    wget curl unzip sqlite3 htop tmux
ok "System packages installed."

# ── Step 2: Python venv ────────────────────────────────────────────────────────
info "Step 2/8 — Creating Python 3.11 virtual environment..."
cd "$PROJECT_DIR"
python3.11 -m venv venv
ok "Venv created at $PROJECT_DIR/venv"

# ── Step 3: Python dependencies ───────────────────────────────────────────────
info "Step 3/8 — Installing Python dependencies..."
source "$PROJECT_DIR/venv/bin/activate"
pip install --upgrade pip wheel setuptools -q
pip install -r "$PROJECT_DIR/requirements.txt" -q
ok "Python dependencies installed."

# ── Step 4: .env file ─────────────────────────────────────────────────────────
info "Step 4/8 — Creating .env configuration file..."

if [[ -f "$PROJECT_DIR/.env" ]]; then
  echo ""
  echo "⚠️  .env already exists. Skipping to avoid overwriting."
  echo "   Edit it manually: nano $PROJECT_DIR/.env"
else
  # Auto-generate a secure API key
  GENERATED_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")

  cat > "$PROJECT_DIR/.env" << EOF
# ── VitalHealth Production Config ────────────────────────────────────────────
# Generated by setup.sh on $(date)
# KEEP THIS FILE SECRET — do not commit to git

DIGITAL_TWIN_API_KEY=$GENERATED_KEY
SIM_RATE_LIMIT=10
SIM_RATE_WINDOW=3600
BIOGEARS_BIN_DIR=$PROJECT_DIR/biogears_runtime
EOF

  chmod 600 "$PROJECT_DIR/.env"
  ok ".env created."
  echo ""
  echo "  ┌──────────────────────────────────────────────────────────┐"
  echo "  │  🔑 YOUR API KEY (save this — you'll need it in the app) │"
  echo "  │                                                           │"
  echo "  │  $GENERATED_KEY  │"
  echo "  │                                                           │"
  echo "  └──────────────────────────────────────────────────────────┘"
  echo ""
fi

# ── Step 5: Verify BioGears runtime ───────────────────────────────────────────
info "Step 5/8 — Checking BioGears runtime..."
RUNTIME_DIR="$PROJECT_DIR/biogears_runtime"
BGCLI="$RUNTIME_DIR/bg-cli"

if [[ ! -f "$BGCLI" ]]; then
  echo -e "${YELLOW}→  BioGears runtime not found. Downloading official Linux release (this may take a minute)...${NC}"
  mkdir -p "$RUNTIME_DIR"
  cd "$RUNTIME_DIR"
  # Download the official BioGears 7.4 Linux binary
  wget -q --show-progress -O biogears.tar.gz "https://github.com/BioGearsEngine/core/releases/download/v7.4.0/BioGears-7.4.0-Linux.tar.gz"
  # Extract it (strip-components removes the top-level folder from the tar so files go directly into biogears_runtime)
  tar -xzf biogears.tar.gz --strip-components=1
  rm biogears.tar.gz
  cd "$PROJECT_DIR"
fi

chmod +x "$BGCLI"
ok "BioGears runtime is ready and executable."

# ── Step 6: Systemd service ────────────────────────────────────────────────────
info "Step 6/8 — Installing systemd service..."
sudo cp "$DEPLOY_DIR/digitaltwin.service" /etc/systemd/system/digitaltwin.service
sudo systemctl daemon-reload
sudo systemctl enable digitaltwin
sudo systemctl restart digitaltwin
sleep 3

if sudo systemctl is-active --quiet digitaltwin; then
  ok "digitaltwin.service is running."
else
  echo ""
  fail "Service failed to start. Check logs: journalctl -u digitaltwin -n 50"
fi

# ── Step 7: Nginx ─────────────────────────────────────────────────────────────
info "Step 7/8 — Configuring Nginx..."
sudo cp "$DEPLOY_DIR/nginx.conf" /etc/nginx/sites-available/digitaltwin
sudo ln -sf /etc/nginx/sites-available/digitaltwin /etc/nginx/sites-enabled/digitaltwin
sudo rm -f /etc/nginx/sites-enabled/default

if sudo nginx -t 2>/dev/null; then
  sudo systemctl reload nginx
  sudo systemctl enable nginx
  ok "Nginx configured and reloaded."
else
  fail "Nginx config test failed. Check: sudo nginx -t"
fi

# ── Step 8: Daily backup cron ─────────────────────────────────────────────────
info "Step 8/8 — Setting up daily backup..."

BACKUP_SCRIPT="/home/ubuntu/backup_twins.sh"
cat > "$BACKUP_SCRIPT" << BSCRIPT
#!/bin/bash
DATE=\$(date +%Y%m%d_%H%M)
DEST="/home/ubuntu/backups/\$DATE"
mkdir -p "\$DEST"
cp -r "$PROJECT_DIR/clinical_data"   "\$DEST/" 2>/dev/null || true
cp    "$PROJECT_DIR/twins_database.db" "\$DEST/" 2>/dev/null || true
cp -r "$PROJECT_DIR/reports"         "\$DEST/" 2>/dev/null || true
ls -dt /home/ubuntu/backups/*/ 2>/dev/null | tail -n +8 | xargs rm -rf
echo "[\$(date)] Backup complete: \$DEST" >> /var/log/twin_backup.log
BSCRIPT

chmod +x "$BACKUP_SCRIPT"
# Schedule: daily at 03:00 AM (only add if not already present)
if ! crontab -l 2>/dev/null | grep -q "backup_twins"; then
  (crontab -l 2>/dev/null; echo "0 3 * * * $BACKUP_SCRIPT") | crontab -
fi
ok "Daily backup cron scheduled (03:00 AM)."

# ── Final health check ─────────────────────────────────────────────────────────
echo ""
info "Running health check..."
sleep 2
HEALTH=$(curl -s http://localhost:8000/health 2>/dev/null || echo "FAIL")

if echo "$HEALTH" | grep -q '"healthy"'; then
  ok "Health check PASSED: $HEALTH"
else
  echo -e "${RED}✘  Health check failed. Response: $HEALTH${NC}"
  echo "   Check logs: journalctl -u digitaltwin -f"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo -e "${GREEN}  ✅  Setup complete!${NC}"
echo "============================================================"
echo ""
echo "  Next steps:"
echo "  1. Open port 80 and 443 in the E2E Cloud Security Group"
echo "  2. Test from your laptop: curl http://YOUR_VM_IP/health"
echo "  3. (Optional) SSL: sudo certbot --nginx -d yourdomain.com"
echo "  4. Update the mobile app URL in Settings → Server Configuration"
echo ""
echo "  Useful commands:"
echo "    journalctl -u digitaltwin -f    # live logs"
echo "    sudo systemctl status digitaltwin"
echo "    sudo systemctl restart digitaltwin"
echo ""
