"""
healthbot_v4/apps/notification/dynamic_notification_generator.py
==================================================================
AI-Powered Dynamic Notification Copy Generator for VitalHealth.
Generates context-aware, witty, clinical, or empathetic notification titles,
body text, emojis, deep links, interactive action buttons, and AI rationale metadata.
"""

from __future__ import annotations
import json
import logging
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional
from uuid import uuid4

logger = logging.getLogger(__name__)

# Valid Persona Tones
TONE_WITTY = "witty"          # Zomato/Swiggy style, gamified, energetic
TONE_CLINICAL = "clinical"    # Precise, direct, medical-grade
TONE_GENTLE = "gentle"        # Soft, empathetic wellness companion
TONE_ADAPTIVE = "adaptive"    # Auto-adjust tone based on urgency

DEFAULT_FALLBACK_NOTIFICATIONS = {
    "medication": {
        "witty": {
            "title": "Time for your daily power-up! 💊",
            "body": "Hey {name}! Your {medicine_name} ({dose}) is waiting. Take it now so your health stats stay in god-mode! ⚡",
            "emoji": "💊",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "taken", "title": "Take Dose 💊", "action": "TAKE_MEDICATION"},
                {"id": "snooze", "title": "Snooze 15m ⏰", "action": "SNOOZE_15M"}
            ],
            "aiRationale": "Routine medication schedule"
        },
        "clinical": {
            "title": "Medication Due: {medicine_name}",
            "body": "Scheduled dose of {medicine_name} ({dose}) is due now. Please confirm administration to maintain therapeutic efficacy.",
            "emoji": "📋",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "taken", "title": "Confirm Administration", "action": "TAKE_MEDICATION"},
                {"id": "snooze", "title": "Snooze 15m", "action": "SNOOZE_15M"}
            ],
            "aiRationale": "Clinical regimen protocol"
        },
        "gentle": {
            "title": "A gentle reminder for your wellness 🌸",
            "body": "Hi {name}, when you have a moment, please remember your {medicine_name} ({dose}). Caring for yourself is your top priority today.",
            "emoji": "🌸",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "taken", "title": "Taken 💊", "action": "TAKE_MEDICATION"},
                {"id": "snooze", "title": "Remind Me Later", "action": "SNOOZE_15M"}
            ],
            "aiRationale": "Empathetic health check-in"
        }
    },
    "interaction_guard": {
        "witty": {
            "title": "Food-Drug Interaction Warning! 🍊⚠️",
            "body": "Whoops {name}! You logged {food_item}. Remember to hold off on your {medicine_name} for 4 hours so they don't fight inside! 🥊",
            "emoji": "⚠️",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "got_it", "title": "Understood 👍", "action": "DISMISS"},
                {"id": "check_twin", "title": "Ask AI Twin 🤖", "action": "OPEN_AI_CHAT"}
            ],
            "aiRationale": "Real-time Pharmacokinetic Safety Guard"
        },
        "clinical": {
            "title": "Clinical Contraindication Warning",
            "body": "Ingestion of {food_item} alters bio-absorption of {medicine_name}. Please delay dose administration by at least 4 hours.",
            "emoji": "🚨",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "got_it", "title": "Acknowledge", "action": "DISMISS"},
                {"id": "check_twin", "title": "View Interaction Details", "action": "OPEN_AI_CHAT"}
            ],
            "aiRationale": "Pharmacokinetic Interaction Safety Lock"
        }
    },
    "digital_twin": {
        "witty": {
            "title": "Glucose Twin Prediction 📈⚡",
            "body": "Hey {name}, your Digital Twin predicts a {predicted_value} mg/dL post-lunch spike. A quick 10-minute walk now will crush that peak by 25 mg/dL! 🏃‍♂️💨",
            "emoji": "🤖",
            "deepLink": "/(tabs)/twin",
            "actionButtons": [
                {"id": "walk", "title": "Log 10m Walk 👟", "action": "LOG_ACTIVITY"},
                {"id": "view_twin", "title": "View Twin Graph 📊", "action": "OPEN_TWIN"}
            ],
            "aiRationale": "Generated by BioGears Physiological Twin Model"
        },
        "clinical": {
            "title": "Digital Twin Simulation: Glycemic Trend",
            "body": "Simulated postprandial glucose trajectory predicts peak of {predicted_value} mg/dL. Mild aerobic activity recommended to enhance insulin sensitivity.",
            "emoji": "📊",
            "deepLink": "/(tabs)/twin",
            "actionButtons": [
                {"id": "view_twin", "title": "Inspect Simulation", "action": "OPEN_TWIN"}
            ],
            "aiRationale": "BioGears Dynamic Physiological Simulation"
        }
    },
    "refill": {
        "witty": {
            "title": "Pill Cabinet Running Low! 📦",
            "body": "Alert {name}! Only {pills_left} pills left of {medicine_name} ({days_left} days supply). Tap to 1-click refill before you run dry! 🚀",
            "emoji": "💊",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "refill", "title": "Refill Now 📦", "action": "REFILL_MEDICINE"}
            ],
            "aiRationale": "Smart Pill Counter & Inventory Forecasting"
        },
        "clinical": {
            "title": "Prescription Refill Warning",
            "body": "Inventory count for {medicine_name} is currently at {pills_left} doses. Please reorder to ensure continuous therapy.",
            "emoji": "📦",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "refill", "title": "Reorder Prescription", "action": "REFILL_MEDICINE"}
            ],
            "aiRationale": "Pharmacy Refill Inventory Threshold"
        }
    },
    "sleep_circadian": {
        "witty": {
            "title": "Time to recharge your battery! 🌙",
            "body": "Hey {name}! Screen-free wind-down starts now. Give your brain 45 minutes of rest so tomorrow is a high-energy day! ⚡",
            "emoji": "🌙",
            "deepLink": "/(tabs)/index",
            "actionButtons": [
                {"id": "wind_down", "title": "Wind-Down Mode 🌙", "action": "START_WIND_DOWN"}
            ],
            "aiRationale": "Circadian Rhythm Optimization"
        },
        "clinical": {
            "title": "Circadian Wind-Down Protocol",
            "body": "Initiating pre-sleep dimming cycle to facilitate endogenous melatonin secretion and optimize REM sleep architecture.",
            "emoji": "🛌",
            "deepLink": "/(tabs)/index",
            "actionButtons": [
                {"id": "wind_down", "title": "Acknowledge", "action": "START_WIND_DOWN"}
            ],
            "aiRationale": "Pineal Gland Melatonin Protocol"
        }
    },
    "lab_fasting": {
        "witty": {
            "title": "Fasting Window Active! 💧",
            "body": "Water-only mode engaged, {name}! Holding off on food tonight means super-accurate lab results tomorrow morning! 🎯",
            "emoji": "🩸",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "timer", "title": "Fasting Timer Active 💧", "action": "START_FASTING_TIMER"}
            ],
            "aiRationale": "Lab Test Fasting Compliance"
        },
        "clinical": {
            "title": "Pre-Analytical Fasting Protocol",
            "body": "Water-only fasting is required for 10 hours prior to blood specimen collection.",
            "emoji": "📋",
            "deepLink": "/(tabs)/vault",
            "actionButtons": [
                {"id": "timer", "title": "Log Fasting Start", "action": "START_FASTING_TIMER"}
            ],
            "aiRationale": "Clinical Lab Pre-Analytical Requirement"
        }
    },
    "stress_reset": {
        "witty": {
            "title": "60-Second Vagal Reset 🧘‍♂️",
            "body": "Autonomic stress spike caught on radar, {name}! Take 4 deep box breaths right now to lower your heart rate! 💨",
            "emoji": "🧘‍♂️",
            "deepLink": "/(tabs)/index",
            "actionButtons": [
                {"id": "breathe", "title": "Start 60s Breathing 🫁", "action": "START_BOX_BREATHING"}
            ],
            "aiRationale": "Autonomic Stress Reset Sensor"
        },
        "clinical": {
            "title": "Parasympathetic Vagal Tone Activation",
            "body": "Transient decrease in HRV detected. 60 seconds of controlled 4-second square breathing recommended.",
            "emoji": "🫁",
            "deepLink": "/(tabs)/index",
            "actionButtons": [
                {"id": "breathe", "title": "Initiate Square Breathing", "action": "START_BOX_BREATHING"}
            ],
            "aiRationale": "Autonomic HRV Vagal Reset"
        }
    },
    "family_milestone": {
        "witty": {
            "title": "Family Victory! 🎉",
            "body": "High-five alert! {name} just hit a massive health streak! Send them some love right now! 👏",
            "emoji": "🎉",
            "deepLink": "/(tabs)/index",
            "actionButtons": [
                {"id": "high_five", "title": "Send High-Five 👏", "action": "SEND_HIGH_FIVE"}
            ],
            "aiRationale": "Family Social Engagement Loop"
        },
        "clinical": {
            "title": "Family Member Adherence Milestone",
            "body": "{name} has maintained 100% protocol adherence for 7 consecutive days.",
            "emoji": "👏",
            "deepLink": "/(tabs)/index",
            "actionButtons": [
                {"id": "high_five", "title": "Send Congratulation", "action": "SEND_HIGH_FIVE"}
            ],
            "aiRationale": "Social Support Reinforcement"
        }
    }
}


class DynamicNotificationGenerator:
    """Dynamic Notification Copy Generator combining LLM prompt synthesis & template fallbacks."""

    @staticmethod
    def resolve_effective_tone(requested_tone: str, priority: str) -> str:
        """Adaptive tone resolution: If tone is 'adaptive', emergency/critical defaults to clinical; routine defaults to witty."""
        if requested_tone != TONE_ADAPTIVE:
            return requested_tone if requested_tone in [TONE_WITTY, TONE_CLINICAL, TONE_GENTLE] else TONE_WITTY
        if priority in ["critical", "high"]:
            return TONE_CLINICAL
        return TONE_WITTY

    @classmethod
    async def generate(
        cls,
        category: str,
        user_name: str = "User",
        priority: str = "medium",
        tone_preference: str = TONE_ADAPTIVE,
        context_data: Optional[Dict[str, Any]] = None,
        llm_orchestrator: Optional[Any] = None
    ) -> Dict[str, Any]:
        """
        Generate dynamic notification object.
        """
        context_data = context_data or {}
        effective_tone = cls.resolve_effective_tone(tone_preference, priority)
        
        # 1. Attempt LLM generation if orchestrator is available
        if llm_orchestrator is not None and hasattr(llm_orchestrator, "generate_notification_copy"):
            try:
                llm_response = await llm_orchestrator.generate_notification_copy(
                    category=category,
                    user_name=user_name,
                    priority=priority,
                    tone=effective_tone,
                    context=context_data
                )
                if llm_response and isinstance(llm_response, dict) and "title" in llm_response:
                    return {
                        "id": str(uuid4()),
                        "title": llm_response.get("title"),
                        "body": llm_response.get("body"),
                        "category": category,
                        "priority": priority,
                        "tone": effective_tone,
                        "emoji": llm_response.get("emoji", "🔔"),
                        "deepLink": llm_response.get("deepLink", "/(tabs)/index"),
                        "actionButtons": llm_response.get("actionButtons", []),
                        "aiRationale": llm_response.get("aiRationale", "Generated by PHOS Reasoning Engine"),
                        "timestamp": datetime.now(timezone.utc).isoformat()
                    }
            except Exception as e:
                logger.warning(f"LLM Dynamic Notification generation failed, using dynamic template fallback: {e}")

        # 2. Template Fallback
        cat_templates = DEFAULT_FALLBACK_NOTIFICATIONS.get(category, DEFAULT_FALLBACK_NOTIFICATIONS["medication"])
        template: Dict[str, Any] = {}
        if isinstance(cat_templates, dict):
            raw_t = cat_templates.get(effective_tone, cat_templates.get("witty", list(cat_templates.values())[0] if cat_templates else {}))
            if isinstance(raw_t, dict):
                template = raw_t
            elif isinstance(raw_t, list) and len(raw_t) > 0 and isinstance(raw_t[0], dict):
                template = raw_t[0]
        elif isinstance(cat_templates, list) and len(cat_templates) > 0 and isinstance(cat_templates[0], dict):
            template = cat_templates[0]

        name = user_name or "there"
        med_name = context_data.get("medicine_name", "your medicine")
        dose = context_data.get("dose", "1 dose")
        food_item = context_data.get("food_item", "food item")
        predicted_val = str(context_data.get("predicted_value", "160"))
        pills_left = str(context_data.get("pills_left", "3"))
        days_left = str(context_data.get("days_left", "2"))

        raw_title = template.get("title", "Health Notification") if isinstance(template, dict) else "Health Notification"
        if isinstance(raw_title, list):
            raw_title = raw_title[0] if raw_title else "Health Notification"

        raw_body = template.get("body", "Scheduled health reminder") if isinstance(template, dict) else "Scheduled health reminder"
        if isinstance(raw_body, list):
            raw_body = raw_body[0] if raw_body else "Scheduled health reminder"

        title = str(raw_title).format(name=name, medicine_name=med_name, dose=dose)
        body = str(raw_body).format(
            name=name,
            medicine_name=med_name,
            dose=dose,
            food_item=food_item,
            predicted_value=predicted_val,
            pills_left=pills_left,
            days_left=days_left
        )

        return {
            "id": str(uuid4()),
            "title": title,
            "body": body,
            "category": category,
            "priority": priority,
            "tone": effective_tone,
            "emoji": template.get("emoji", "🔔"),
            "deepLink": template.get("deepLink", "/(tabs)/index"),
            "actionButtons": template.get("actionButtons", []),
            "aiRationale": template.get("aiRationale", "PHOS Dynamic Safety Engine"),
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
